seed: [ 1, 2, 3 ]
device: [ cpu ]
root_dir: [ output/grid_1 ]
dataset:
  name: [ cifar10, mnist, lsun ]
  root: [ ../Data ]
  splits: [ [ 0.8, 0.1, 0.1 ] ]
  k_fold: [ 1 ]
  shuffle_train: [ True ]
  loss: [ default ]
  scale: [ default ]
model:
  name: [ image_classifier ]
  layer_name: [ cnn, resnet, lene t ]
  dim_inner: [ 64, 256 ]
  num_layers: [ 2, 10 ]
  init: [ None, xavier ]
  act: [ elu, relu ]
train:
  max_epochs: [ 300 ]
  batch_size: [ 256 ]
  max_time: [ 00:24:00:00 ]
  enable_progress_bar: [ False ]
early_stopping:
  activate: [ False ]
  min_delta: [ 0.0 ]
  patience: [ 100 ]
  verbose: [ False ]
optim:
  optimizer: [ adam ]
  base_lr: [ 1e-2 ]
  beta_1: [ 0.9 ]
  beta_2: [ 0.999 ]
  momentum: [ 0.0 ]
  weight_decay: [ 0.0 ]
  scheduler: [ plateau ]
  gamma: [ 0.99 ]
  step_size: [ 100 ]
  mode: [ min ]
  factor: [ 0.99 ]
  patience: [ 20 ]
  cooldown: [ 0 ]